apiVersion: apps/v1
kind: Deployment
metadata:
  name: expensy-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: expensy-backend
  template:
    metadata:
      labels:
        app: expensy-backend
    spec:
      containers:
      - name: backend
        image: lordvetonn/expensy-backend:v1
        ports:
        - containerPort: 3001
        env:
        - name: DATABASE_URI
          value: "mongodb://mongo:27017/expensy"
        - name: REDIS_HOST
          value: "redis"
        - name: REDIS_PASSWORD
          value: "someredispassword"
        readinessProbe:
          httpGet:
            path: /api/expenses
            port: 3001
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 2
          successThreshold: 3
          failureThreshold: 3
        livenessProbe:
          tcpSocket:
            port: 3001
          initialDelaySeconds: 20
          periodSeconds: 20
          timeoutSeconds: 2
          failureThreshold: 3
        resources:
          requests:
            cpu: "100m"
            memory: "256Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: expensy-backend
spec:
  type: ClusterIP
  selector:
    app: expensy-backend
  ports:
  - port: 3001
    targetPort: 3001
