apiVersion: apps/v1
kind: Deployment
metadata:
  name: expensy-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: expensy-frontend
  template:
    metadata:
      labels:
        app: expensy-frontend
    spec:
      containers:
      - name: frontend
        image: lordvetonn/expensy-frontend:v1
        ports:
        - containerPort: 3000
        env:
        - name: NEXT_PUBLIC_API_URL
          value: "http://expensy-backend:3001/api"
---
apiVersion: v1
kind: Service
metadata:
  name: expensy-frontend
spec:
  type: LoadBalancer
  selector:
    app: expensy-frontend
  ports:
  - port: 80
    targetPort: 3000
