name: CD - Deploy to AKS
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Azure login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Set AKS context
        uses: azure/aks-set-context@v4
        with:
          resource-group: ${{ secrets.AKS_RESOURCE_GROUP }}
          cluster-name: ${{ secrets.AKS_CLUSTER_NAME }}

      - name: Update backend image
        run: |
          kubectl set image deploy/expensy-backend \
            expensy-backend=lordvetonn/expensy-backend:${{ github.sha }} \
            -n ${{ secrets.K8S_NAMESPACE }}

      - name: Update frontend image
        run: |
          kubectl set image deploy/expensy-frontend \
            expensy-frontend=lordvetonn/expensy-frontend:${{ github.sha }} \
            -n ${{ secrets.K8S_NAMESPACE }}

      - name: Wait for rollout
        run: |
          kubectl rollout status deploy/expensy-backend -n ${{ secrets.K8S_NAMESPACE }}
          kubectl rollout status deploy/expensy-frontend -n ${{ secrets.K8S_NAMESPACE }}
